package it.tlogic.aoo.dao;

import java.math.BigInteger;

import it.tlogic.aoo.model.Aoo;
import it.tlogic.aoo.model.Titolario;

public interface AooDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table aoo
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    void insert(Aoo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table aoo
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    int updateByPrimaryKey(Aoo record);

     /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table aoo
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    Aoo selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table aoo
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    int deleteByPrimaryKey(Long id);
    
    
    Aoo selectByName(String name);

	int addTitolario(Titolario tit, Aoo aoo);

	String getTitolarioJournal(String aoo);
    
    
    
    
    
}