package it.tlogic.aoo.dao;

import it.tlogic.aoo.model.Counter;


import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CounterDAOImpl extends SqlMapClientDaoSupport implements CounterDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public CounterDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public void insert(Counter record) {
		getSqlMapClientTemplate().insert("counter.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public int updateByPrimaryKey(Counter record) {
		int rows = getSqlMapClientTemplate().update(
				"counter.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public Counter selectByPrimaryKey(Long id) {
		Counter key = new Counter();
		key.setId(id);
		Counter record = (Counter) getSqlMapClientTemplate().queryForObject(
				"counter.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public int deleteByPrimaryKey(Long id) {
		Counter key = new Counter();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"counter.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}
	
	public Counter selectByAoo(String aooName) {
		Counter record = (Counter) getSqlMapClientTemplate().queryForObject(
				"counter.selectByAoo", aooName);
		return record;
	}
	
	public int increment(Counter counterObj) {
		int rows = getSqlMapClientTemplate().update(
				"counter.abatorgenerated_updateByPrimaryKey", counterObj);
		return rows;
	}
	
	public Counter addCounter(String name) {
		Counter counterObj = new Counter();
		counterObj.setLastvalue(new Long(1));
		getSqlMapClientTemplate().insert("counter.abatorgenerated_insert", counterObj);
		//counterObj.setId(idNew.longValue());
		
		Map map = new HashMap<String, Object>();
		map.put("COUNTER_ID", counterObj.getId());
		map.put("AOO_NAME", name);
		
		
		getSqlMapClientTemplate().insert("counter.insertAoRelation", map);
		
		return counterObj;
	}
	
	
}