package it.tlogic.aoo.dao;

import it.tlogic.aoo.model.Counter;

import java.util.List;

public interface CounterDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	void insert(Counter record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	int updateByPrimaryKey(Counter record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	Counter selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table counter
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	int deleteByPrimaryKey(Long id);
	
	Counter selectByAoo(String aooName);

	int increment(Counter counterObj);

	Counter addCounter(String name);
	
}