package it.tlogic.aoo.dao;

import it.tlogic.aoo.model.TitolarioTree;

public interface TitolarioTreeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table titolario_tree
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    void insert(TitolarioTree record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table titolario_tree
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    int updateByPrimaryKey(TitolarioTree record);


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table titolario_tree
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    TitolarioTree selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table titolario_tree
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    int deleteByPrimaryKey(Long id);
}