package it.tlogic.aoo.model;

import java.util.List;

public class Aoo {
	
	
	private Titolario titolario;
	
    public Titolario getTitolario() {
		return titolario;
	}

	public void setTitolario(Titolario titolario) {
		this.titolario = titolario;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column aoo.ID
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column aoo.NAME
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column aoo.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    private String description;

	private String titolarioJournal;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column aoo.ID
     *
     * @return the value of aoo.ID
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column aoo.ID
     *
     * @param id the value for aoo.ID
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column aoo.NAME
     *
     * @return the value of aoo.NAME
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column aoo.NAME
     *
     * @param name the value for aoo.NAME
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column aoo.DESCRIPTION
     *
     * @return the value of aoo.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column aoo.DESCRIPTION
     *
     * @param description the value for aoo.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

	public String getTitolarioJournal() {
		// TODO Auto-generated method stub
		return titolarioJournal;
	}

	public void setTitolarioJournal(String titolarioJournal) {
		this.titolarioJournal = titolarioJournal;
	}


}