package it.tlogic.aoo.model;

public class Counter {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column counter.ID
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column counter.LASTVALUE
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	private Long lastvalue;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column counter.ID
	 * @return  the value of counter.ID
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column counter.ID
	 * @param id  the value for counter.ID
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column counter.LASTVALUE
	 * @return  the value of counter.LASTVALUE
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public Long getLastvalue() {
		return lastvalue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column counter.LASTVALUE
	 * @param lastvalue  the value for counter.LASTVALUE
	 * @abatorgenerated  Wed Mar 21 17:27:12 CET 2012
	 */
	public void setLastvalue(Long lastvalue) {
		this.lastvalue = lastvalue;
	}
}