package it.tlogic.aoo.model;

import java.util.List;

public class Titolario {
	
	
	private List<TitolarioTree> titolarioTree;
	
    public List<TitolarioTree> getTitolarioTree() {
		return titolarioTree;
	}

	public void setTitolarioTree(List<TitolarioTree> titolarioTree) {
		
		this.titolarioTree = titolarioTree;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario.ID
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario.NAME
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario.DESCR
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    private String descr;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario.ID
     *
     * @return the value of titolario.ID
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario.ID
     *
     * @param id the value for titolario.ID
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario.NAME
     *
     * @return the value of titolario.NAME
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario.NAME
     *
     * @param name the value for titolario.NAME
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario.DESCR
     *
     * @return the value of titolario.DESCR
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario.DESCR
     *
     * @param descr the value for titolario.DESCR
     *
     * @abatorgenerated Wed Mar 21 17:27:12 CET 2012
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }
}