package it.tlogic.aoo.model;

import java.util.List;

public class TitolarioTree {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario_tree.ID
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario_tree.TITOLARIO_ID
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    private Long titolarioId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario_tree.ID_OWNER
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    private Long idOwner;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario_tree.NAME
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column titolario_tree.DESCR
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    private String descr;

    private List<TitolarioTree> child;
    
    public List<TitolarioTree> getChild() {
		return child;
	}

	public void setChild(List<TitolarioTree> child) {
		this.child = child;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario_tree.ID
     *
     * @return the value of titolario_tree.ID
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario_tree.ID
     *
     * @param id the value for titolario_tree.ID
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario_tree.TITOLARIO_ID
     *
     * @return the value of titolario_tree.TITOLARIO_ID
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public Long getTitolarioId() {
        return titolarioId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario_tree.TITOLARIO_ID
     *
     * @param titolarioId the value for titolario_tree.TITOLARIO_ID
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public void setTitolarioId(Long titolarioId) {
        this.titolarioId = titolarioId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario_tree.ID_OWNER
     *
     * @return the value of titolario_tree.ID_OWNER
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public Long getIdOwner() {
        return idOwner;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario_tree.ID_OWNER
     *
     * @param idOwner the value for titolario_tree.ID_OWNER
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public void setIdOwner(Long idOwner) {
        this.idOwner = idOwner;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario_tree.NAME
     *
     * @return the value of titolario_tree.NAME
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario_tree.NAME
     *
     * @param name the value for titolario_tree.NAME
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column titolario_tree.DESCR
     *
     * @return the value of titolario_tree.DESCR
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column titolario_tree.DESCR
     *
     * @param descr the value for titolario_tree.DESCR
     *
     * @abatorgenerated Thu Mar 22 14:59:42 CET 2012
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }
}